### ISSUE TITLE
What are the thresholds for low- and moderate-income in Chicago?

### ISSUE THREAD

**Issue by dtburk** [zorostang/chicago_bike_equity#11]
We are getting income data from the ACS, which reports income in about 10 or 11 categories. We may want to make arguments involving low- and moderate-income populations, so we need to determine what the commonly-used thresholds for these categories are.

**Comment by Oboi** [comment]
@dtb557 Suggest we group low-income pop and moderate-income pop into a broader LMI pop. Most federal, state, city agencies do the same. And, most rational people consider moderate-income people in Chicago as poor. Found the definitions for both low-income and moderate-income here: 
https://www2.fdic.gov/crapes/peterms.asp

Here you go... 

Low-Income: individuals and geographies having a median family income less than 50 percent of the area median income.

Median Income: the median income divides the income distribution into two equal parts, one having incomes above the median and other having incomes below the median.

**Comment by dtburk** [comment]
Thanks @Oboi ! From your FDIC source:

"Moderate-Income: individuals and geographies having a median family income of at least 50 percent and less than 80 percent of the area median income."

So if we group together low- and moderate-income, it seems like an LMI Census tract would be any tract with median income less than 80 percent of the median income for Cook County/City of Chicago as a whole.

**Comment by Oboi** [comment]
Hey @dtb557 - Yep, this is generally the approach federal, state, city depts, as well as the banking industry takes in assessing LMI pops. Feels like the right approach for us.

**Comment by stevevance** [comment]
Okay, we'll use 80 percent of median income and group low and moderate into the same. Closing the issue now!
