### ISSUE TITLE
Can we connect biking to crime-reduction via research on the link between health and crime-reduction?

### ISSUE THREAD

**Issue by dtburk** [zorostang/chicago_bike_equity#12]
This is a research-group question that we could create a wiki page for, perhaps titled "Biking and Crime", where we can collect research findings that point to biking as a force for crime-reduction.

**Comment by dtburk** [comment]
What are the findings on bike lanes and biking in Bogota, Colombia?

**Comment by Oboi** [comment]
@dtb557 Peace Derek - Lots out there. Check out the term "ciclovia bogota". Will also send you some research on this. Thanks mane, peace...

**Comment by stevevance** [comment]
Did we conclude anything on this topic?
Is it still the case that there's not enough research to support this connection?
