### ISSUE TITLE
How many grocery stores have a Divvy station nearby?

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#13]
Another problem we can solve with Turf.js.

**Comment by guillermokrh** [comment]
Hey Steven, I added a "turf-tests" branch, so I can show you what I'm trying to do with turf.  Right now I'm struggling with iterating through the list of groceries to use them as comparison points in turf.  For example, in the console right now I can access the latitude of the grocery store at index 0 of the groceriesGeojson feature list by typing in "groceriesGeojson.features[0].properties.LATITUDE".  But when I try to use this information in the code, groceriesGeojson always turns up as undefined.  Is there a better way of interacting with this data?

**Comment by zorostang** [comment]
@guillermokrh checkout my latest commit to turf-tests. I experimented with turf and divvy and was able to iterate through all the divvy stations and create 0.2 mile buffer regions using turf. This technique could probably be mimicked for the grocery stores.

**Comment by guillermokrh** [comment]
Thanks Gino I'll check it out!

**Comment by stevevance** [comment]
@zorostang Can you show me tomorrow? I'm gonna be coding tomorrow with you guys, something I haven't done for weeks because of...distractions at Hack Night.

**Comment by stevevance** [comment]
Done. @guillermokrh made it so the number would be calculated and then printed it to the console. See another issue for the next step.

**Comment by stevevance** [comment]
Done. @guillermokrh made it so the number would be calculated and then printed it to the console. See another issue for the next step.
