### ISSUE TITLE
Add a Divvy service area of 2 miles around the stations

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#19]
Currently there's a Divvy buffer area of 0.5 miles around each station, which represents the walk shed (the distance most people would walk from their home to the Divvy station, or from the Divvy station to the workplace). 

There should be a second layer (of a different style) that shows a presumed Divvy service area of 2 miles (the distance you can travel in 30 minutes). 

This is definitely going to be inaccurate, because a station on the edge should only have a service area oriented toward other stations.

**Comment by SyedSufyan** [comment]
We can try calculating the distance traveled in 30 minutes, by taking the average speed of the people driving bikes. I think we can generate this average, by using the divvy data we have. the time taken from one station to another.

**Comment by stevevance** [comment]
@SyedSufyan Sounds like a potential solution. @thcrock has another idea. 

This is a low-priority feature, but if you can solve it easily, do it.
