### ISSUE TITLE
need geojson

### ISSUE THREAD

**Issue by MMenninger** [zorostang/chicago_bike_equity#2]
this file needs a geojson

**Comment by MMenninger** [comment]
also - confirm projection on all files

**Comment by stevevance** [comment]
Which file, @MMenninger?

**Comment by MMenninger** [comment]
i just made them all. figuring out how to upload.

**Comment by MMenninger** [comment]
Posted the files on dropbox. Will check in tomorrow to see if they work and try to see if I can upload.

**Comment by stevevance** [comment]
Files are here:
https://github.com/MMenninger/QGISwork
