### ISSUE TITLE
Pop-up Divvy station names when the cursor is hovered on the Divvy station

### ISSUE THREAD

**Issue by SyedSufyan** [zorostang/chicago_bike_equity#21]
I was thinking that if we can get the station names showing on the screen when we hover the cursor on the station, like we did for the grocery stores, that would be a good add on, let me know what you think.
note : minor fix for the location of script in html file.

**Comment by stevevance** [comment]
@SyedSufyan I think this is a good idea to improve the user experience. 

The code that does this for the grocery stores is highly reusable and was provided by the "Bootleaf" application. Can you adapt that code from the grocery stores?

**Comment by thcrock** [comment]
Even better; would it be helpful to merge in some aggregates per station from the Divvy Data Challenge? Avg trips per day, etc? It might come in handy for illustrating current bike usage.

**Comment by stevevance** [comment]
@SyedSufyan Don't do that now.

**Comment by SyedSufyan** [comment]
ok but why, do we have another requirement now. Also, I have another Idea, we can search bike stations, not just by right clicking, also by search with respect to the area code or zip code. what do you think. @stevevance

**Comment by stevevance** [comment]
@SyedSufyan Divvy stations aren't a priority. Until we know their effect on bike lane distribution, and what the research group tells us, the map should only show their location (and details like name/address). 

How's your progress on showing their names when you hover them?

**Comment by SyedSufyan** [comment]
@stevevance well, I have researched some of the ways to show the names of the station, but nothing materialistic happened. We can start working on other issues right now, if we have time later on, we can come back to this one. Let me know what issue are we currently looking at, btw I have removed the search box :)
