### ISSUE TITLE
Add a location search for users to find their home or workplace

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#24]
The fastest way to do this would be to use one of the several Leaflet plugins that adds a "search" control box as an overlay on the map. 

Also, remove the "Search" box in the upper-right corner because it's misleading on what it does. (The search box on the left side should remain.)

**Comment by easherma** [comment]
I think this is pretty easy to do. I can export a layer from qgis2leaf that
includes a location search.

On Tuesday, March 10, 2015, Steven Vance notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/zorostang/chicago_bike_equity/issues/24.

## 

Eric Sherman
224-402-0004

This e-mail, and any attachments thereto, is intended only for use by
the addressee(s) named herein and may contain legally privileged
and/or confidential information. If you are not the intended recipient
of this e-mail (or the person responsible for delivering this document
to the intended recipient), you are hereby notified that any
dissemination, distribution, printing or copying of this e-mail, and
any attachment thereto, is strictly prohibited. If you have received
this e-mail in error, please respond to the individual sending the
message, and permanently delete the original and any copy of any
e-mail and printout thereof.

**Comment by stevevance** [comment]
@easherma I'm interested in seeing how qgis2leaf (QGIS to Leaflet) works, and I'm a little surprised that it comes with a location search. Is that location search specific to the layer that you export?

**Comment by SyedSufyan** [comment]
@stevevance Top right Search box Removed
