### ISSUE TITLE
What can we use from this Hardship Index map to inform our Access Index?

### ISSUE THREAD

**Issue by kuhnbaya** [zorostang/chicago_bike_equity#32]
Hi all,

The research group discussed this map of a Hardship Index. We thought there were a couple of good things on this map that we can use: 

http://www.chicagomag.com/Chicago-Magazine/The-312/May-2012/The-Geography-of-Economic-Hardship-in-Chicago/
1. Color spectrum: We liked that the Hardship Index map had a wide spectrum of colors. It seems like it is easier to read because the colors are very different. 
2. Community area boundaries: The Hardship Index map uses community areas instead of census tracts. Can we do this on our map? We thought the maps would load faster (less data) and it might be easier for the viewer to read with less boundarie (cleaner map).

**Comment by dtburk** [comment]
I was just looking at the map and I agree with Mary that the default boundaries should be community area and not Ward or Census tract. Those smaller geographies could be an option, but I think community areas should be the default.

**Comment by stevevance** [comment]
@dtb557 I think we should have both Wards and Community Areas available. I believe that we will have interest from aldermen who will need info specific to their geography.
