### ISSUE TITLE
Turn the "reverse geocode" function into the beginning of the "Get Access Index" function

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#36]
1. In the context menu, change to "Get an Access Index"
2. Combine the "nearest Divvy stations" and "show address" functions into a new function called something like, "getAccessIndex()". 
3. Count the number of grocery stores within 2 miles of this point. 
4. When you click on an address in the "Access Index" sidebar, highlight the corresponding map marker.

**Comment by guillermokrh** [comment]
Hey Steve,

While you're at it, you might want to change the permissions for my account in terms of merging privileges. I'm totally fine with keeping things the way they are and dealing with merging conflicts as they arise, but you might want to be the clearinghouse for that because I might not know what changes you'll want to keep at the moment. This could be important as we start working on parts individually during the week (as I'll be doing with the stuff you assigned to me).

**Comment by stevevance** [comment]
@guillermokrh I'm not sure what your privileges are now. Do you have direct access to pushing commits?

**Comment by guillermokrh** [comment]
I do have direct access to pushing commits, so I think I have "collaborator" access.  I think only Gino can control who is a collaborator, and who can only send pull requests.

**Comment by stevevance** [comment]
@zorostang Can you take Guillermo off "collaborator" access, per his request?

**Comment by guillermokrh** [comment]
Update
1. In the context menu, change to "Get an Access Index" - done
2. Combine the "nearest Divvy stations" and "show address" functions into a new function called something like, "getAccessIndex()". -todo
3. Count the number of grocery stores within 2 miles of this point. -todo
4. When you click on an address in the "Access Index" sidebar, highlight the corresponding map marker. -todo
5. Make button for "clear indices" - done

**Comment by guillermokrh** [comment]
Update
1. In the context menu, change to "Get an Access Index" - done
2. Combine the "nearest Divvy stations" and "show address" functions into a new function called something like, "getAccessIndex()". -todo
3. Count the number of grocery stores within 2 miles of this point. -todo
4. When you click on an address in the "Access Index" sidebar, highlight the corresponding map marker. -todo
5. Make button for "clear indices" - done

**Comment by stevevance** [comment]
Awesome, @guillermokrh. Let's review this tomorrow night.
