### ISSUE TITLE
Why does ESRI's reverse geocoder fail sometimes?

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#38]
Occasionally the reverse geocode function fails to produce a response. 

Is our JavaScript looking for the right response codes/statuses and does it know what to do with the "wrong" response?

**Comment by guillermokrh** [comment]
Update: Figured out the error that it throws, working on printing out a nice message that says something to the effect of "try again".

**Comment by stevevance** [comment]
@guillermokrh What error was it throwing?

Would it be possible to "try again" without requested that the user do anything?

**Comment by guillermokrh** [comment]
![screen shot 2015-04-21 at 7 50 28 pm](https://cloud.githubusercontent.com/assets/8136798/7265444/c28e14c6-e85f-11e4-9f47-5f9c03388260.png)

**Comment by guillermokrh** [comment]
I think it is possible to try again, but shouldn't we let the user know that there is no data for the specific location they are requesting?

**Comment by stevevance** [comment]
@guillermokrh Ife was working on this today, setting up a new geocoder with Pelias, actually. I'm going to go ahead and close it.
