### ISSUE TITLE
Transcribe bike counts into a Google Spreadsheet

### ISSUE THREAD

**Issue by rguico** [zorostang/chicago_bike_equity#41]
Source: http://www.scribd.com/doc/240207885/2014-09-BikeCount

Spreadsheet: https://docs.google.com/spreadsheets/d/1mGFX0Lak4jnxvbWNzuBervyGuswq5hrMyQMIxzS7JVs/edit?usp=sharing

**Comment by stevevance** [comment]
I added in the missing December 2013 document numbers.
