### ISSUE TITLE
Add half-mile bike lane buffer to the map

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#46]
So we can visualize if there really are 2.1 million people within a half mile of a bike lane. This will eventually be used in the API to determine if the desired point is within a half mile of a bike lane or not. 

Use Turf.js to add a buffer to the bike lanes of half mile. Use the `buffer` function to draw a buffer shape of 2,640 feet around the bike lanes. 

```
// buffer the bike lanes
var buffered= turf.buffer(bike_lanes, 2640, "feet");

bike_lanes_buffered = new L.GeoJSONLayer(buffered);
map.addLayer(bike_lanes_buffered);
```

**Comment by Sonju** [comment]
We ran the buffer function, however, Turf took over a minute to process and create the bike lane buffer.  At this pace it would not produce a good user experience. 

Turf creates buffers in polygon forms and bike lanes are single straight lines. This is one reason for its lengthy processing speed. We a made a decision to utilize a traditional GIS software to build the bike lane buffer.

**Comment by stevevance** [comment]
We're going to try another method, and that's getting the distance to the nearest bike lane. Then testing if it's less than or greater than half a mile. We already have a "get distance" function for the Divvy stations, so it should be easy to implement this (now issue #50).
