### ISSUE TITLE
Get distance to the nearest bike lane and add this to the Access Index

### ISSUE THREAD

**Issue by stevevance** [zorostang/chicago_bike_equity#50]
See issue #46 for why we abandoned that issue and created this issue. 

Concept: We need to know if someone (their house, or whichever point they choose) is within 1/2 mile of a bike lane or not. The `turf.buffer` function didn't work, so we're going to use the same `turf.distance` function that we're using to calculate the distance to the nearest Divvy stations.

**Comment by easherma** [comment]
An issue here will probably be that its more costly to measure the distance
from a poin to a line than from point to point. One way around this would
be to calculate/precalculate the midpoint of each bike lane segment and
measure the distance from your arbitrary point to that midpoint. That would
still be pretty costly so youd either index the midpoints or have the turf
code only generate midpoints on line segments within .5 miles of where you
click.

On Tuesday, April 28, 2015, Steven Vance notifications@github.com wrote:

> See issue #46 https://github.com/zorostang/chicago_bike_equity/issues/46
> for why we abandoned that issue and created this issue.
> 
> Concept: We need to know if someone (their house, or whichever point they
> choose) is within 1/2 mile of a bike lane or not. The turf.buffer
> function didn't work, so we're going to use the same turf.distance
> function that we're using to calculate the distance to the nearest Divvy
> stations.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zorostang/chicago_bike_equity/issues/50.

## 

Eric Sherman
224-402-0004

This e-mail, and any attachments thereto, is intended only for use by
the addressee(s) named herein and may contain legally privileged
and/or confidential information. If you are not the intended recipient
of this e-mail (or the person responsible for delivering this document
to the intended recipient), you are hereby notified that any
dissemination, distribution, printing or copying of this e-mail, and
any attachment thereto, is strictly prohibited. If you have received
this e-mail in error, please respond to the individual sending the
message, and permanently delete the original and any copy of any
e-mail and printout thereof.

**Comment by stevevance** [comment]
@easherma I believe, too, it might be costly to measure. It might be useful to make a hidden GeoJSON layer that's all the bike lanes as one MultiLineString line. 

Also, Sonju (I can't tag you!), the `turf.distance` function won't work for this as it requires two points, and can't deal with a point and a string. 

Try `turf.point-on-line``. However, this may not work because this only works with a point and a LineString line (bike lanes have a MultiLineString form).

The bike lanes' MultiLineString form could be disaggregated somehow, perhaps using `turf.explode`.

**Comment by Sonju** [comment]
Hey @stevevance I just subscribed to the notifications. Do I need to activate something so you can "tag" me?

**Comment by stevevance** [comment]
Done. Ended up using CartoDB. We wasted too much time trying to figure out a way to do this in Turf!
