### ISSUE TITLE
add legend

### ISSUE THREAD

**Issue by derekeder** [zorostang/chicago_bike_equity#6]
![screen shot 2015-01-26 at 2 17 27 pm](https://cloud.githubusercontent.com/assets/919583/5907634/1723d7f6-a566-11e4-9b0c-e193876270d6.png)
At first glance, its unclear what I'm looking at.

Include a legend for your default layers: population density and bike lanes. What do the colors mean?

**Comment by stevevance** [comment]
Look for inspiration for a legend within [this Leaflet tutorial](http://leafletjs.com/examples/choropleth.html).

**Comment by rguico** [comment]
I think I'll lead the coding team on Tuesday to pick this one up.

**Comment by SyedSufyan** [comment]
@rguico are we planning to add legend as a part of the map, or just a documentation ? what I was thinking is a way to make a static legend image, and then find a way to put that image in the map. what do you think.

**Comment by rguico** [comment]
Syed - we want to use http://leafletjs.com/examples/choropleth.html but
tonight we worked to generate a GeoJSON file that we can refer to as a
source for that map.

A dynamic solution would be nice because we can reuse it when we start
putting out other layers besides population density.

-Robert

**Comment by SyedSufyan** [comment]
@rguico sounds good, see ya guys next week, and finish this thing up :)

**Comment by stevevance** [comment]
This is the wrong legend to add. We will be adding a different legend through another issue using @rguico's chloropleth map.
